name: Create Release, Build and Push Docker Images to Docker Hub

on:
  workflow_dispatch:

env:
  REGISTRY: docker.io
  IMAGE_NAME: cognirum/pgvector

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false   # Ensure jobs don't stop if one fails
      matrix:
        pg_version: ["17.0", "16.4", "15.8", "14.13", "13.16", "12.20"]
        variant: [base, alpine, bullseye, bookworm]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the Docker image
        run: |
          # Select Dockerfile based on the variant
          if [ "${{ matrix.variant }}" = "base" ]; then
            DOCKERFILE=Dockerfile
          elif [ "${{ matrix.variant }}" = "alpine" ]; then
            DOCKERFILE=Dockerfile.alpine
          else
            DOCKERFILE=Dockerfile.bullseye
          fi

          # Build the Docker image with the appropriate tag
          docker build \
            --build-arg PG_VERSION=${{ matrix.pg_version }} \
            -f $DOCKERFILE \
            -t ${{ env.IMAGE_NAME }}:${{ matrix.pg_version }}-${{ matrix.variant }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Base image to Docker Hub
        if: matrix.variant == 'base'
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ matrix.pg_version }}

      - name: Push Docker alternative image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ matrix.pg_version }}-${{ matrix.variant }}

      # Tag and push "latest" for the 17.0 version
      - name: Tag the image as latest
        if: matrix.pg_version == '17.0' && matrix.variant == 'base' # Only for 17.0 default flavor
        run: |
          docker tag ${{ env.IMAGE_NAME }}:17.0 ${{ env.IMAGE_NAME }}:latest

      - name: Push latest tag to Docker Hub
        if: matrix.pg_version == '17.0' && matrix.variant == 'base' # Only for 17.0 default flavor
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest

  changelog:
    needs: build_and_push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install semantic-release globally
        run: npm install -g semantic-release @semantic-release/changelog @semantic-release/github @semantic-release/exec @semantic-release/git

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Generate changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release --no-ci